### ISSUE TITLE
Hopper - Week Zero

### ISSUE THREAD

**Issue by TylerSeiford** [FRCTeam2501/2020-Robot#18]
1. As with #17 , this code needs to be reformatted with respect to the `ports.h`, `include.h`, folder structure, and passing `Pneumatics` as a pointer.
2. Currently, this subsystem has no functioning actions, merely a placeholder function.  We should probably add a good amount of functions to it.
3. Functions should be PascalCase.
4. The motors should be `WPI_TalonSRX`s instead of `PWMVictorSPX`s, and we should probably just call them "front" and "back" to simplify.

**Comment by parker-nelson** [comment]
uh oh sitnky mnke hahahahahahahahahaahahahahahaha
